import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";

import { Card, CardContent } from "@/components/ui/card";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Streamer's Edge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="fixed right-4 top-4 z-50 w-72">
          <Card className="bg-white/90 backdrop-blur">
            <CardContent className="space-y-2 p-4 text-sm">
              <p className="font-medium">Please help me get a job</p>
              <p className="text-muted-foreground">
                Star my projects on{" "}
                <a
                  className="underline underline-offset-4"
                  href="https://github.com/obelisk2u"
                  target="_blank"
                  rel="noreferrer"
                >
                  github.com/obelisk2u
                </a>
              </p>
            </CardContent>
          </Card>
        </div>
        {children}
      </body>
    </html>
  );
}
